export enum ActionType {
    GET_USERS_REQUEST = 'users/GET_USERS_REQUEST',
    GET_USERS_CANCEL = 'users/GET_USERS_CANCEL',
    GET_USERS_DONE = 'users/GET_USERS_DONE',
    GET_USERS_FAIL = 'users/GET_USERS_FAIL'
}